apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coreops-vigilante.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreops-vigilante.labels" . | nindent 4 }}
data:
  conf.yaml: |
    {{ toYaml .Values.config | nindent 8 }}