apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coreops-vigilante.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreops-vigilante.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coreops-vigilante.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coreops-vigilante.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
{{ if .Values.create_certificates }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTPS
{{ else }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
{{ end }}
          volumeMounts:
{{ if .Values.create_certificates }}
            - name: tls-certs
              mountPath: /etc/vigilante/certs
              readOnly: true
{{ end }}
            - name: config-file
              mountPath: /etc/vigilante/config
              readOnly: true
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{ if .Values.create_certificates }}
        - name: tls-certs
          secret:
            secretName: {{ include "coreops-vigilante.fullname" . }}-tls
{{ end }}
        - name: config-file
          configMap:
            name: {{ include "coreops-vigilante.fullname" . }}
      nodeSelector:
        kubernetes.io/os: linux
