apiVersion: v1
kind: Service
metadata:
  name: {{ include "coreops-vigilante.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreops-vigilante.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "coreops-vigilante.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
{{ if .Values.create_certificates }}
      port: 443
{{ else }}
      port: 80
{{ end }}
      targetPort: http
      name: http
