apiVersion: v1
kind: Service
metadata:
  name: {{ include "coreops-vigilante.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreops-vigilante.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "coreops-vigilante.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ 443 }}
      targetPort: http
      name: http
