{{ if .Values.create_service_monitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "coreops-vigilante.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coreops-vigilante.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coreops-vigilante.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      honorLabels: true
{{ end }}
{{ if and .Values.create_service_monitor .Values.create_certificates }} # nested ifs not working
      scheme: https
      tlsConfig:
         insecureSkipVerify: true
{{ end }}